# Generated by Django 3.1.4 on 2021-03-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('extraverted', 'extraverted'), ('introverted', 'introverted'), ('intuitive', 'intuitive'), ('sensing', 'sensing'), ('thinking', 'thinking'), ('feeling', 'feeling'), ('judging', 'judging'), ('perceiving', 'perceiving')], max_length=200),
        ),
    ]
