# Generated by Django 3.1.4 on 2021-03-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210301_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='quiztaker',
            name='score',
        ),
        migrations.AddField(
            model_name='answer',
            name='scoring',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='extraverted_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
