# Generated by Django 3.1.4 on 2021-03-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210301_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='feeling_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='introverted_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='intuitive_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='judging_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='perceiving_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='sensing_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='thinking_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
