# Generated by Django 3.1.4 on 2021-03-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiztaker',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiztaker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='usersanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='usersanswer',
            name='quiz_taker',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizTaker',
        ),
        migrations.DeleteModel(
            name='UsersAnswer',
        ),
    ]
