# Generated by Django 3.1.4 on 2021-03-01 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personality', '0002_auto_20210301_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('scoring', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('extraverted', 'extraverted'), ('introverted', 'introverted'), ('intuitive', 'intuitive'), ('sensing', 'sensing'), ('thinking', 'thinking'), ('feeling', 'feeling'), ('judging', 'judging'), ('perceiving', 'perceiving')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(blank=True)),
                ('roll_out', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizTaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introverted_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('extraverted_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('intuitive_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sensing_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('thinking_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('feeling_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('judging_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('perceiving_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('completed', models.BooleanField(default=False)),
                ('date_finished', models.DateTimeField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personality.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personality.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personality.question')),
                ('quiz_taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personality.quiztaker')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personality.quiz'),
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_letter', models.CharField(max_length=70)),
                ('second_letter', models.CharField(max_length=70)),
                ('third_letter', models.CharField(max_length=70)),
                ('fourth_letter', models.CharField(max_length=70)),
                ('type_personality', models.CharField(blank=True, choices=[('entp', 'entp'), ('intp', 'intp')], max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personality.question'),
        ),
    ]
